server:
  port: 8888
spring:
  profiles:
    active: git, vault
  cloud:
    config:
      server:
        # git config
        git:
          uri: ${GIT_URI:https://github.optum.com/sbagrec1/config-repo}
          order: 2
        # vault config
        vault:
          host: ${VAULT_HOST:127.0.0.1}
          port: ${VAULT_PORT:8200}
          kv-version: 2
          order: 1




